server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: chert-host-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: chert
          __path__: /var/log/chert/**/*.log*

    pipeline_stages:
      # tracing-subscriber JSON format roughly:
      # {"timestamp":...,"level":...,"fields":{...},"target":...,"span":...,"spans":[...]}
      - json:
          expressions:
            level: level
            target: target
            msg: fields.message
      - labels:
          level:
          target:
      - output:
          source: msg
